// <auto-generated />
using System;
using KontaktyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KontaktyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526111613_PrvniMigrace")]
    partial class PrvniMigrace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("KontaktyAPI.Models.Kontakt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kontakty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Libora61@gmail.com",
                            Jmeno = "Libora",
                            Mesto = "Štramberk",
                            Prijmeni = "Vlk",
                            Telefon = "993 289 857",
                            VytvorenoAt = new DateTime(2026, 1, 27, 9, 47, 53, 108, DateTimeKind.Local).AddTicks(7539)
                        },
                        new
                        {
                            Id = 2,
                            Email = "Ivar_Bares86@volny.cz",
                            Jmeno = "Ivar",
                            Mesto = "Neveklov",
                            Prijmeni = "Bareš",
                            Telefon = "493 526 513",
                            VytvorenoAt = new DateTime(2025, 9, 8, 22, 3, 35, 896, DateTimeKind.Local).AddTicks(6762)
                        },
                        new
                        {
                            Id = 3,
                            Email = "Zdana37@volny.cz",
                            Jmeno = "Ždana",
                            Mesto = "Hlučín",
                            Prijmeni = "Hrdá",
                            Telefon = "558 941 829",
                            VytvorenoAt = new DateTime(2024, 6, 16, 21, 3, 58, 968, DateTimeKind.Local).AddTicks(7843)
                        },
                        new
                        {
                            Id = 4,
                            Email = "Dag.Neumanova@seznam.cz",
                            Jmeno = "Dag",
                            Mesto = "Zábřeh",
                            Prijmeni = "Neumanová",
                            Telefon = "404 434 249",
                            VytvorenoAt = new DateTime(2026, 1, 1, 23, 51, 32, 53, DateTimeKind.Local).AddTicks(2872)
                        },
                        new
                        {
                            Id = 5,
                            Email = "Jarmil.Stoklasova@atlas.cz",
                            Jmeno = "Jarmil",
                            Mesto = "Kamenice nad Lipou",
                            Prijmeni = "Stoklasová",
                            Telefon = "534 819 434",
                            VytvorenoAt = new DateTime(2025, 2, 17, 2, 4, 46, 147, DateTimeKind.Local).AddTicks(5670)
                        },
                        new
                        {
                            Id = 6,
                            Email = "Adolfina.Fouskova57@seznam.cz",
                            Jmeno = "Adolfína",
                            Mesto = "Fulnek",
                            Prijmeni = "Fousková",
                            Telefon = "073 669 994",
                            VytvorenoAt = new DateTime(2025, 3, 5, 18, 27, 11, 616, DateTimeKind.Local).AddTicks(6976)
                        },
                        new
                        {
                            Id = 7,
                            Email = "Cistoslav_Kralickova@volny.cz",
                            Jmeno = "Čistoslav",
                            Mesto = "Sedlice",
                            Prijmeni = "Králíčková",
                            Telefon = "872 748 168",
                            VytvorenoAt = new DateTime(2024, 8, 23, 0, 58, 7, 91, DateTimeKind.Local).AddTicks(5190)
                        },
                        new
                        {
                            Id = 8,
                            Email = "Miloslav_Brizova5@volny.cz",
                            Jmeno = "Miloslav",
                            Mesto = "Nový Knín",
                            Prijmeni = "Břízová",
                            Telefon = "548 923 161",
                            VytvorenoAt = new DateTime(2024, 6, 29, 13, 28, 30, 884, DateTimeKind.Local).AddTicks(376)
                        },
                        new
                        {
                            Id = 9,
                            Email = "Veleslav99@seznam.cz",
                            Jmeno = "Veleslav",
                            Mesto = "Zbýšov",
                            Prijmeni = "Křeček",
                            Telefon = "231 443 166",
                            VytvorenoAt = new DateTime(2025, 9, 21, 15, 0, 5, 926, DateTimeKind.Local).AddTicks(730)
                        },
                        new
                        {
                            Id = 10,
                            Email = "Muriel.Mikula61@volny.cz",
                            Jmeno = "Muriel",
                            Mesto = "Čelákovice",
                            Prijmeni = "Mikula",
                            Telefon = "103 527 460",
                            VytvorenoAt = new DateTime(2025, 3, 30, 14, 31, 45, 536, DateTimeKind.Local).AddTicks(2827)
                        },
                        new
                        {
                            Id = 11,
                            Email = "Artur70@centrum.cz",
                            Jmeno = "Artur",
                            Mesto = "Horní Jiřetín",
                            Prijmeni = "Maleček",
                            Telefon = "269 938 520",
                            VytvorenoAt = new DateTime(2024, 10, 11, 22, 27, 12, 3, DateTimeKind.Local).AddTicks(2137)
                        },
                        new
                        {
                            Id = 12,
                            Email = "Volfgang.Studnickova35@gmail.com",
                            Jmeno = "Volfgang",
                            Mesto = "Kardašova Řečice",
                            Prijmeni = "Studničková",
                            Telefon = "625 144 771",
                            VytvorenoAt = new DateTime(2024, 10, 26, 21, 26, 36, 186, DateTimeKind.Local).AddTicks(2761)
                        },
                        new
                        {
                            Id = 13,
                            Email = "Teodor_Holik40@atlas.cz",
                            Jmeno = "Teodor",
                            Mesto = "Třebechovice pod Orebem",
                            Prijmeni = "Holík",
                            Telefon = "729 747 281",
                            VytvorenoAt = new DateTime(2025, 10, 14, 6, 28, 32, 691, DateTimeKind.Local).AddTicks(6924)
                        },
                        new
                        {
                            Id = 14,
                            Email = "Klaudian81@volny.cz",
                            Jmeno = "Klaudián",
                            Mesto = "Mariánské Lázně",
                            Prijmeni = "Štěpán",
                            Telefon = "122 242 425",
                            VytvorenoAt = new DateTime(2026, 5, 23, 18, 4, 15, 702, DateTimeKind.Local).AddTicks(8774)
                        },
                        new
                        {
                            Id = 15,
                            Email = "Berta60@centrum.cz",
                            Jmeno = "Berta",
                            Mesto = "Lomnice nad Popelkou",
                            Prijmeni = "Vojtíšek",
                            Telefon = "665 650 872",
                            VytvorenoAt = new DateTime(2025, 9, 22, 12, 21, 24, 688, DateTimeKind.Local).AddTicks(3187)
                        },
                        new
                        {
                            Id = 16,
                            Email = "Felician63@gmail.com",
                            Jmeno = "Felicián",
                            Mesto = "Lázně Bohdaneč",
                            Prijmeni = "Píša",
                            Telefon = "370 821 269",
                            VytvorenoAt = new DateTime(2024, 6, 23, 17, 57, 2, 539, DateTimeKind.Local).AddTicks(215)
                        },
                        new
                        {
                            Id = 17,
                            Email = "Radivoj_Hrdina43@centrum.cz",
                            Jmeno = "Radivoj",
                            Mesto = "Jirkov",
                            Prijmeni = "Hrdina",
                            Telefon = "464 801 677",
                            VytvorenoAt = new DateTime(2025, 3, 23, 9, 34, 53, 864, DateTimeKind.Local).AddTicks(7502)
                        },
                        new
                        {
                            Id = 18,
                            Email = "Dalie_Vanova71@volny.cz",
                            Jmeno = "Dalie",
                            Mesto = "Tišnov",
                            Prijmeni = "Váňová",
                            Telefon = "767 617 805",
                            VytvorenoAt = new DateTime(2024, 7, 29, 3, 2, 24, 539, DateTimeKind.Local).AddTicks(8601)
                        },
                        new
                        {
                            Id = 19,
                            Email = "Edvarda18@seznam.cz",
                            Jmeno = "Edvarda",
                            Mesto = "Domažlice",
                            Prijmeni = "Pšeničková",
                            Telefon = "272 108 131",
                            VytvorenoAt = new DateTime(2026, 5, 4, 11, 15, 59, 156, DateTimeKind.Local).AddTicks(3792)
                        },
                        new
                        {
                            Id = 20,
                            Email = "Agata_Dockal73@atlas.cz",
                            Jmeno = "Agáta",
                            Mesto = "Fryšták",
                            Prijmeni = "Dočkal",
                            Telefon = "751 076 665",
                            VytvorenoAt = new DateTime(2024, 8, 13, 11, 25, 27, 198, DateTimeKind.Local).AddTicks(8029)
                        },
                        new
                        {
                            Id = 21,
                            Email = "Pelagie49@gmail.com",
                            Jmeno = "Pelagie",
                            Mesto = "Nymburk",
                            Prijmeni = "Tomková",
                            Telefon = "740 030 764",
                            VytvorenoAt = new DateTime(2025, 6, 22, 10, 9, 5, 684, DateTimeKind.Local).AddTicks(7919)
                        },
                        new
                        {
                            Id = 22,
                            Email = "Ctislava_Sevcikova41@seznam.cz",
                            Jmeno = "Ctislava",
                            Mesto = "Plzeň",
                            Prijmeni = "Ševčíková",
                            Telefon = "292 578 161",
                            VytvorenoAt = new DateTime(2026, 4, 3, 14, 14, 26, 94, DateTimeKind.Local).AddTicks(7263)
                        },
                        new
                        {
                            Id = 23,
                            Email = "Aron_Synek93@centrum.cz",
                            Jmeno = "Áron",
                            Mesto = "Rožmberk nad Vltavou",
                            Prijmeni = "Synek",
                            Telefon = "393 942 734",
                            VytvorenoAt = new DateTime(2026, 4, 12, 5, 34, 26, 887, DateTimeKind.Local).AddTicks(2249)
                        },
                        new
                        {
                            Id = 24,
                            Email = "Venceslav82@gmail.com",
                            Jmeno = "Věnceslav",
                            Mesto = "Kunovice",
                            Prijmeni = "Mrázková",
                            Telefon = "663 043 808",
                            VytvorenoAt = new DateTime(2025, 6, 25, 0, 1, 53, 688, DateTimeKind.Local).AddTicks(9627)
                        },
                        new
                        {
                            Id = 25,
                            Email = "Dino_Dolejsova@centrum.cz",
                            Jmeno = "Dino",
                            Mesto = "Strážov",
                            Prijmeni = "Dolejšová",
                            Telefon = "987 889 257",
                            VytvorenoAt = new DateTime(2024, 8, 14, 3, 35, 8, 70, DateTimeKind.Local).AddTicks(1005)
                        },
                        new
                        {
                            Id = 26,
                            Email = "Veduna.Smutny@volny.cz",
                            Jmeno = "Věduna",
                            Mesto = "Třeboň",
                            Prijmeni = "Smutný",
                            Telefon = "397 176 113",
                            VytvorenoAt = new DateTime(2026, 3, 20, 14, 10, 4, 804, DateTimeKind.Local).AddTicks(4471)
                        },
                        new
                        {
                            Id = 27,
                            Email = "Abraham.Karlova42@volny.cz",
                            Jmeno = "Abraham",
                            Mesto = "Hluk",
                            Prijmeni = "Karlová",
                            Telefon = "521 905 074",
                            VytvorenoAt = new DateTime(2025, 1, 15, 23, 5, 8, 125, DateTimeKind.Local).AddTicks(5378)
                        },
                        new
                        {
                            Id = 28,
                            Email = "Vilmar.Kubelkova33@gmail.com",
                            Jmeno = "Vilmar",
                            Mesto = "Bílina",
                            Prijmeni = "Kubelková",
                            Telefon = "160 166 762",
                            VytvorenoAt = new DateTime(2024, 7, 2, 2, 20, 39, 11, DateTimeKind.Local).AddTicks(8221)
                        },
                        new
                        {
                            Id = 29,
                            Email = "Vlastimila.Jansky@atlas.cz",
                            Jmeno = "Vlastimila",
                            Mesto = "Kdyně",
                            Prijmeni = "Jánský",
                            Telefon = "542 426 588",
                            VytvorenoAt = new DateTime(2025, 12, 9, 11, 58, 28, 925, DateTimeKind.Local).AddTicks(393)
                        },
                        new
                        {
                            Id = 30,
                            Email = "Serafina.Reznickova@atlas.cz",
                            Jmeno = "Serafína",
                            Mesto = "Krásné Údolí",
                            Prijmeni = "Řezníčková",
                            Telefon = "121 383 300",
                            VytvorenoAt = new DateTime(2025, 7, 8, 22, 50, 36, 597, DateTimeKind.Local).AddTicks(2088)
                        },
                        new
                        {
                            Id = 31,
                            Email = "Romana.Podzimek@seznam.cz",
                            Jmeno = "Romana",
                            Mesto = "Hustopeče",
                            Prijmeni = "Podzimek",
                            Telefon = "368 118 120",
                            VytvorenoAt = new DateTime(2024, 8, 18, 7, 1, 11, 291, DateTimeKind.Local).AddTicks(3149)
                        },
                        new
                        {
                            Id = 32,
                            Email = "Rebeka16@volny.cz",
                            Jmeno = "Rebeka",
                            Mesto = "Trhový Štěpánov",
                            Prijmeni = "Černá",
                            Telefon = "971 423 811",
                            VytvorenoAt = new DateTime(2025, 10, 8, 4, 43, 51, 877, DateTimeKind.Local).AddTicks(1314)
                        },
                        new
                        {
                            Id = 33,
                            Email = "Brian_Rada91@gmail.com",
                            Jmeno = "Brian",
                            Mesto = "Přibyslav",
                            Prijmeni = "Rada",
                            Telefon = "104 940 421",
                            VytvorenoAt = new DateTime(2025, 12, 30, 11, 31, 27, 380, DateTimeKind.Local).AddTicks(2220)
                        },
                        new
                        {
                            Id = 34,
                            Email = "Eduard69@atlas.cz",
                            Jmeno = "Eduard",
                            Mesto = "Zákupy",
                            Prijmeni = "Smolka",
                            Telefon = "974 771 080",
                            VytvorenoAt = new DateTime(2026, 1, 20, 9, 5, 24, 462, DateTimeKind.Local).AddTicks(3715)
                        },
                        new
                        {
                            Id = 35,
                            Email = "Marcela_Kuzelova@volny.cz",
                            Jmeno = "Marcela",
                            Mesto = "Třebechovice pod Orebem",
                            Prijmeni = "Kuželová",
                            Telefon = "712 322 170",
                            VytvorenoAt = new DateTime(2025, 9, 30, 19, 51, 46, 742, DateTimeKind.Local).AddTicks(2572)
                        },
                        new
                        {
                            Id = 36,
                            Email = "Simona82@centrum.cz",
                            Jmeno = "Šimona",
                            Mesto = "Krásné Údolí",
                            Prijmeni = "Peřinová",
                            Telefon = "555 842 170",
                            VytvorenoAt = new DateTime(2026, 2, 16, 17, 20, 48, 586, DateTimeKind.Local).AddTicks(3662)
                        },
                        new
                        {
                            Id = 37,
                            Email = "Neklan70@volny.cz",
                            Jmeno = "Neklan",
                            Mesto = "Pacov",
                            Prijmeni = "Kala",
                            Telefon = "519 651 149",
                            VytvorenoAt = new DateTime(2024, 8, 26, 6, 30, 24, 573, DateTimeKind.Local).AddTicks(8933)
                        },
                        new
                        {
                            Id = 38,
                            Email = "Borislav.Kosova13@gmail.com",
                            Jmeno = "Borislav",
                            Mesto = "Rotava",
                            Prijmeni = "Kosová",
                            Telefon = "272 310 256",
                            VytvorenoAt = new DateTime(2024, 9, 17, 3, 47, 59, 814, DateTimeKind.Local).AddTicks(996)
                        },
                        new
                        {
                            Id = 39,
                            Email = "Jirina_Seda78@gmail.com",
                            Jmeno = "Jiřina",
                            Mesto = "Toužim",
                            Prijmeni = "Šeda",
                            Telefon = "437 728 502",
                            VytvorenoAt = new DateTime(2026, 2, 8, 10, 37, 18, 796, DateTimeKind.Local).AddTicks(2103)
                        },
                        new
                        {
                            Id = 40,
                            Email = "Simona16@seznam.cz",
                            Jmeno = "Simona",
                            Mesto = "Frýdek-Místek",
                            Prijmeni = "Vydra",
                            Telefon = "861 366 464",
                            VytvorenoAt = new DateTime(2025, 8, 3, 21, 15, 33, 398, DateTimeKind.Local).AddTicks(6832)
                        },
                        new
                        {
                            Id = 41,
                            Email = "Rozita51@atlas.cz",
                            Jmeno = "Rozita",
                            Mesto = "Bavorov",
                            Prijmeni = "Dudková",
                            Telefon = "160 503 714",
                            VytvorenoAt = new DateTime(2025, 1, 31, 0, 39, 55, 389, DateTimeKind.Local).AddTicks(4347)
                        },
                        new
                        {
                            Id = 42,
                            Email = "Celestyna_Nova@centrum.cz",
                            Jmeno = "Celestýna",
                            Mesto = "Kolín",
                            Prijmeni = "Nová",
                            Telefon = "041 532 927",
                            VytvorenoAt = new DateTime(2025, 11, 16, 15, 6, 47, 304, DateTimeKind.Local).AddTicks(3046)
                        },
                        new
                        {
                            Id = 43,
                            Email = "Andelin_Spicka67@atlas.cz",
                            Jmeno = "Andělín",
                            Mesto = "Ostrov",
                            Prijmeni = "Špička",
                            Telefon = "693 502 028",
                            VytvorenoAt = new DateTime(2024, 12, 13, 6, 16, 29, 534, DateTimeKind.Local).AddTicks(4664)
                        },
                        new
                        {
                            Id = 44,
                            Email = "Ireneus57@centrum.cz",
                            Jmeno = "Ireneus",
                            Mesto = "Raspenava",
                            Prijmeni = "Sklenářová",
                            Telefon = "193 100 849",
                            VytvorenoAt = new DateTime(2025, 11, 5, 9, 40, 44, 807, DateTimeKind.Local).AddTicks(5819)
                        },
                        new
                        {
                            Id = 45,
                            Email = "Krasava.Zeman30@centrum.cz",
                            Jmeno = "Krasava",
                            Mesto = "Nový Bydžov",
                            Prijmeni = "Zeman",
                            Telefon = "868 373 343",
                            VytvorenoAt = new DateTime(2025, 10, 3, 22, 0, 8, 319, DateTimeKind.Local).AddTicks(657)
                        },
                        new
                        {
                            Id = 46,
                            Email = "Rosa_Kolacek@seznam.cz",
                            Jmeno = "Rosa",
                            Mesto = "Planá nad Lužnicí",
                            Prijmeni = "Koláček",
                            Telefon = "862 572 024",
                            VytvorenoAt = new DateTime(2025, 5, 13, 14, 51, 36, 221, DateTimeKind.Local).AddTicks(4794)
                        },
                        new
                        {
                            Id = 47,
                            Email = "Maxima73@gmail.com",
                            Jmeno = "Maxima",
                            Mesto = "Litvínov",
                            Prijmeni = "Rambousek",
                            Telefon = "411 519 544",
                            VytvorenoAt = new DateTime(2025, 7, 28, 3, 33, 42, 332, DateTimeKind.Local).AddTicks(522)
                        },
                        new
                        {
                            Id = 48,
                            Email = "Leontyn_Sedlak7@centrum.cz",
                            Jmeno = "Leontýn",
                            Mesto = "Solnice",
                            Prijmeni = "Sedlák",
                            Telefon = "347 362 150",
                            VytvorenoAt = new DateTime(2024, 12, 30, 6, 47, 44, 840, DateTimeKind.Local).AddTicks(5988)
                        },
                        new
                        {
                            Id = 49,
                            Email = "Vaclav_Sebestova@atlas.cz",
                            Jmeno = "Václav",
                            Mesto = "Klatovy",
                            Prijmeni = "Šebestová",
                            Telefon = "078 572 152",
                            VytvorenoAt = new DateTime(2024, 10, 28, 16, 40, 3, 841, DateTimeKind.Local).AddTicks(3955)
                        },
                        new
                        {
                            Id = 50,
                            Email = "Noema_Fabian@volny.cz",
                            Jmeno = "Noema",
                            Mesto = "Paskov",
                            Prijmeni = "Fabián",
                            Telefon = "225 597 289",
                            VytvorenoAt = new DateTime(2024, 10, 19, 9, 0, 7, 80, DateTimeKind.Local).AddTicks(2464)
                        },
                        new
                        {
                            Id = 51,
                            Email = "Aglaja_Olah@volny.cz",
                            Jmeno = "Aglaja",
                            Mesto = "Slavkov u Brna",
                            Prijmeni = "Oláh",
                            Telefon = "948 576 834",
                            VytvorenoAt = new DateTime(2024, 7, 28, 7, 36, 19, 800, DateTimeKind.Local).AddTicks(5538)
                        },
                        new
                        {
                            Id = 52,
                            Email = "Stanislav.Zach@volny.cz",
                            Jmeno = "Stanislav",
                            Mesto = "Ledeč nad Sázavou",
                            Prijmeni = "Zach",
                            Telefon = "944 846 003",
                            VytvorenoAt = new DateTime(2025, 12, 3, 14, 51, 49, 330, DateTimeKind.Local).AddTicks(4895)
                        },
                        new
                        {
                            Id = 53,
                            Email = "Alice.Trnkova27@centrum.cz",
                            Jmeno = "Alice",
                            Mesto = "Meziměstí",
                            Prijmeni = "Trnková",
                            Telefon = "526 135 283",
                            VytvorenoAt = new DateTime(2025, 11, 10, 3, 47, 39, 970, DateTimeKind.Local).AddTicks(120)
                        },
                        new
                        {
                            Id = 54,
                            Email = "Geralda67@gmail.com",
                            Jmeno = "Geralda",
                            Mesto = "Třešť",
                            Prijmeni = "Kubicová",
                            Telefon = "773 327 292",
                            VytvorenoAt = new DateTime(2026, 1, 22, 7, 14, 1, 276, DateTimeKind.Local).AddTicks(7947)
                        },
                        new
                        {
                            Id = 55,
                            Email = "Mira.Kotasova57@atlas.cz",
                            Jmeno = "Mira",
                            Mesto = "Varnsdorf",
                            Prijmeni = "Kotasová",
                            Telefon = "324 880 525",
                            VytvorenoAt = new DateTime(2025, 10, 25, 11, 5, 3, 862, DateTimeKind.Local).AddTicks(4056)
                        },
                        new
                        {
                            Id = 56,
                            Email = "Mario61@volny.cz",
                            Jmeno = "Mario",
                            Mesto = "Přebuz",
                            Prijmeni = "Suchomel",
                            Telefon = "702 173 214",
                            VytvorenoAt = new DateTime(2025, 10, 14, 20, 49, 26, 615, DateTimeKind.Local).AddTicks(7934)
                        },
                        new
                        {
                            Id = 57,
                            Email = "Svatoboj.Pilar77@seznam.cz",
                            Jmeno = "Svatoboj",
                            Mesto = "Lázně Bělohrad",
                            Prijmeni = "Pilař",
                            Telefon = "729 895 189",
                            VytvorenoAt = new DateTime(2024, 12, 29, 16, 21, 24, 611, DateTimeKind.Local).AddTicks(8874)
                        },
                        new
                        {
                            Id = 58,
                            Email = "Valerian.Uhrova@seznam.cz",
                            Jmeno = "Valerián",
                            Mesto = "Milevsko",
                            Prijmeni = "Uhrová",
                            Telefon = "069 644 414",
                            VytvorenoAt = new DateTime(2025, 5, 6, 13, 29, 15, 999, DateTimeKind.Local).AddTicks(4733)
                        },
                        new
                        {
                            Id = 59,
                            Email = "Emil49@seznam.cz",
                            Jmeno = "Emil",
                            Mesto = "Klobouky u Brna",
                            Prijmeni = "Mikulášková",
                            Telefon = "037 325 687",
                            VytvorenoAt = new DateTime(2025, 12, 19, 16, 40, 7, 735, DateTimeKind.Local).AddTicks(9330)
                        },
                        new
                        {
                            Id = 60,
                            Email = "Leontyn.Sikorova13@gmail.com",
                            Jmeno = "Leontýn",
                            Mesto = "Neratovice",
                            Prijmeni = "Sikorová",
                            Telefon = "330 591 385",
                            VytvorenoAt = new DateTime(2024, 8, 20, 22, 55, 32, 114, DateTimeKind.Local).AddTicks(1240)
                        },
                        new
                        {
                            Id = 61,
                            Email = "Sixtus.Vojtek75@gmail.com",
                            Jmeno = "Sixtus",
                            Mesto = "Suchdol nad Lužnicí",
                            Prijmeni = "Vojtek",
                            Telefon = "508 165 849",
                            VytvorenoAt = new DateTime(2024, 6, 12, 4, 3, 9, 748, DateTimeKind.Local).AddTicks(9973)
                        },
                        new
                        {
                            Id = 62,
                            Email = "Celestin16@seznam.cz",
                            Jmeno = "Celestin",
                            Mesto = "Kostelec nad Orlicí",
                            Prijmeni = "Karbanová",
                            Telefon = "011 706 582",
                            VytvorenoAt = new DateTime(2025, 10, 4, 20, 14, 57, 400, DateTimeKind.Local).AddTicks(7629)
                        },
                        new
                        {
                            Id = 63,
                            Email = "Slavomil_Janousek@centrum.cz",
                            Jmeno = "Slavomil",
                            Mesto = "Kladruby",
                            Prijmeni = "Janoušek",
                            Telefon = "966 889 387",
                            VytvorenoAt = new DateTime(2025, 7, 25, 23, 21, 42, 587, DateTimeKind.Local).AddTicks(133)
                        },
                        new
                        {
                            Id = 64,
                            Email = "Harold.Hanusova53@centrum.cz",
                            Jmeno = "Harold",
                            Mesto = "Nové Strašecí",
                            Prijmeni = "Hanusová",
                            Telefon = "128 910 077",
                            VytvorenoAt = new DateTime(2025, 3, 20, 17, 18, 42, 199, DateTimeKind.Local).AddTicks(3304)
                        },
                        new
                        {
                            Id = 65,
                            Email = "Alvar_Nedoma61@atlas.cz",
                            Jmeno = "Alvar",
                            Mesto = "Dubí",
                            Prijmeni = "Nedoma",
                            Telefon = "692 315 388",
                            VytvorenoAt = new DateTime(2024, 6, 13, 4, 10, 5, 816, DateTimeKind.Local).AddTicks(3213)
                        },
                        new
                        {
                            Id = 66,
                            Email = "Svetozar_Benesova33@centrum.cz",
                            Jmeno = "Svetozar",
                            Mesto = "Kaplice",
                            Prijmeni = "Benešová",
                            Telefon = "094 265 992",
                            VytvorenoAt = new DateTime(2025, 10, 2, 8, 22, 11, 829, DateTimeKind.Local).AddTicks(8615)
                        },
                        new
                        {
                            Id = 67,
                            Email = "Zoe30@atlas.cz",
                            Jmeno = "Zoe",
                            Mesto = "Bystré",
                            Prijmeni = "Sehnal",
                            Telefon = "800 618 689",
                            VytvorenoAt = new DateTime(2024, 10, 18, 23, 20, 59, 490, DateTimeKind.Local).AddTicks(2741)
                        },
                        new
                        {
                            Id = 68,
                            Email = "Vanda_Klouda@volny.cz",
                            Jmeno = "Vanda",
                            Mesto = "Choceň",
                            Prijmeni = "Klouda",
                            Telefon = "728 107 498",
                            VytvorenoAt = new DateTime(2025, 7, 14, 23, 22, 55, 266, DateTimeKind.Local).AddTicks(4236)
                        },
                        new
                        {
                            Id = 69,
                            Email = "Nila_Zeman90@atlas.cz",
                            Jmeno = "Nila",
                            Mesto = "Dolní Poustevna",
                            Prijmeni = "Zeman",
                            Telefon = "997 020 127",
                            VytvorenoAt = new DateTime(2025, 11, 3, 9, 19, 50, 240, DateTimeKind.Local).AddTicks(1570)
                        },
                        new
                        {
                            Id = 70,
                            Email = "Krasava.Blahova22@gmail.com",
                            Jmeno = "Krasava",
                            Mesto = "Vrchlabí",
                            Prijmeni = "Bláhová",
                            Telefon = "825 380 460",
                            VytvorenoAt = new DateTime(2025, 5, 10, 5, 6, 57, 189, DateTimeKind.Local).AddTicks(8490)
                        },
                        new
                        {
                            Id = 71,
                            Email = "Juda.Hejda10@volny.cz",
                            Jmeno = "Juda",
                            Mesto = "Velké Meziříčí",
                            Prijmeni = "Hejda",
                            Telefon = "438 824 840",
                            VytvorenoAt = new DateTime(2024, 12, 15, 14, 13, 10, 752, DateTimeKind.Local).AddTicks(9815)
                        },
                        new
                        {
                            Id = 72,
                            Email = "Zoroslav.Zdrazilova49@gmail.com",
                            Jmeno = "Zoroslav",
                            Mesto = "Opava",
                            Prijmeni = "Zdražilová",
                            Telefon = "354 549 687",
                            VytvorenoAt = new DateTime(2026, 2, 21, 10, 52, 6, 379, DateTimeKind.Local).AddTicks(8434)
                        },
                        new
                        {
                            Id = 73,
                            Email = "Remig24@volny.cz",
                            Jmeno = "Remig",
                            Mesto = "Slavičín",
                            Prijmeni = "Bednář",
                            Telefon = "107 100 183",
                            VytvorenoAt = new DateTime(2025, 10, 22, 18, 32, 45, 236, DateTimeKind.Local).AddTicks(4886)
                        },
                        new
                        {
                            Id = 74,
                            Email = "Oktavie28@seznam.cz",
                            Jmeno = "Oktavie",
                            Mesto = "Horní Bříza",
                            Prijmeni = "Šafránková",
                            Telefon = "633 279 261",
                            VytvorenoAt = new DateTime(2024, 8, 4, 8, 48, 19, 699, DateTimeKind.Local).AddTicks(412)
                        },
                        new
                        {
                            Id = 75,
                            Email = "Oskar_Blazek@centrum.cz",
                            Jmeno = "Oskar",
                            Mesto = "Vysoké Veselí",
                            Prijmeni = "Blažek",
                            Telefon = "309 631 023",
                            VytvorenoAt = new DateTime(2025, 4, 29, 16, 48, 39, 789, DateTimeKind.Local).AddTicks(5829)
                        },
                        new
                        {
                            Id = 76,
                            Email = "Sabina72@centrum.cz",
                            Jmeno = "Sabina",
                            Mesto = "Kojetín",
                            Prijmeni = "Zálešák",
                            Telefon = "895 094 937",
                            VytvorenoAt = new DateTime(2025, 9, 28, 11, 5, 48, 468, DateTimeKind.Local).AddTicks(6759)
                        },
                        new
                        {
                            Id = 77,
                            Email = "Birgita5@seznam.cz",
                            Jmeno = "Birgita",
                            Mesto = "Chýnov",
                            Prijmeni = "Doleček",
                            Telefon = "873 681 079",
                            VytvorenoAt = new DateTime(2025, 9, 5, 3, 59, 28, 663, DateTimeKind.Local).AddTicks(7009)
                        },
                        new
                        {
                            Id = 78,
                            Email = "Ctirada_Stupkova@centrum.cz",
                            Jmeno = "Ctirada",
                            Mesto = "Třeboň",
                            Prijmeni = "Stupková",
                            Telefon = "212 202 341",
                            VytvorenoAt = new DateTime(2024, 12, 28, 21, 46, 34, 271, DateTimeKind.Local).AddTicks(7987)
                        },
                        new
                        {
                            Id = 79,
                            Email = "Konstancie_Lukasek58@volny.cz",
                            Jmeno = "Konstancie",
                            Mesto = "Sadská",
                            Prijmeni = "Lukášek",
                            Telefon = "264 856 144",
                            VytvorenoAt = new DateTime(2024, 11, 23, 7, 3, 46, 567, DateTimeKind.Local).AddTicks(114)
                        },
                        new
                        {
                            Id = 80,
                            Email = "Florentyna_Truhlarova@atlas.cz",
                            Jmeno = "Florentýna",
                            Mesto = "Pec pod Sněžkou",
                            Prijmeni = "Truhlářová",
                            Telefon = "925 359 729",
                            VytvorenoAt = new DateTime(2024, 11, 23, 14, 36, 44, 243, DateTimeKind.Local).AddTicks(2665)
                        },
                        new
                        {
                            Id = 81,
                            Email = "Zlatan68@centrum.cz",
                            Jmeno = "Zlatan",
                            Mesto = "Hroznětín",
                            Prijmeni = "Matulová",
                            Telefon = "716 695 807",
                            VytvorenoAt = new DateTime(2026, 1, 3, 2, 57, 49, 220, DateTimeKind.Local).AddTicks(5371)
                        },
                        new
                        {
                            Id = 82,
                            Email = "Elfrida.Nesporova21@centrum.cz",
                            Jmeno = "Elfrída",
                            Mesto = "Sadská",
                            Prijmeni = "Nešporová",
                            Telefon = "266 486 060",
                            VytvorenoAt = new DateTime(2026, 1, 11, 15, 29, 12, 33, DateTimeKind.Local).AddTicks(749)
                        },
                        new
                        {
                            Id = 83,
                            Email = "Natalie3@seznam.cz",
                            Jmeno = "Natálie",
                            Mesto = "Kyjov",
                            Prijmeni = "Chromý",
                            Telefon = "836 166 141",
                            VytvorenoAt = new DateTime(2025, 7, 6, 8, 53, 28, 508, DateTimeKind.Local).AddTicks(4054)
                        },
                        new
                        {
                            Id = 84,
                            Email = "Ivo.Truhlar92@centrum.cz",
                            Jmeno = "Ivo",
                            Mesto = "Semily",
                            Prijmeni = "Truhlář",
                            Telefon = "557 764 830",
                            VytvorenoAt = new DateTime(2024, 9, 29, 8, 46, 12, 512, DateTimeKind.Local).AddTicks(955)
                        },
                        new
                        {
                            Id = 85,
                            Email = "Kresomysl_Fialova25@volny.cz",
                            Jmeno = "Křesomysl",
                            Mesto = "Osek",
                            Prijmeni = "Fialová",
                            Telefon = "687 437 738",
                            VytvorenoAt = new DateTime(2025, 1, 19, 23, 7, 37, 665, DateTimeKind.Local).AddTicks(3909)
                        },
                        new
                        {
                            Id = 86,
                            Email = "Gvendolina_Pavlickova@volny.cz",
                            Jmeno = "Gvendolína",
                            Mesto = "Rudná",
                            Prijmeni = "Pavlíčková",
                            Telefon = "922 212 917",
                            VytvorenoAt = new DateTime(2025, 3, 3, 14, 57, 33, 744, DateTimeKind.Local).AddTicks(6913)
                        },
                        new
                        {
                            Id = 87,
                            Email = "Rozvita18@seznam.cz",
                            Jmeno = "Rozvita",
                            Mesto = "Štětí",
                            Prijmeni = "Šišková",
                            Telefon = "124 944 274",
                            VytvorenoAt = new DateTime(2025, 2, 7, 9, 10, 36, 196, DateTimeKind.Local).AddTicks(2899)
                        },
                        new
                        {
                            Id = 88,
                            Email = "Alva76@volny.cz",
                            Jmeno = "Alva",
                            Mesto = "Sokolov",
                            Prijmeni = "Šrámková",
                            Telefon = "210 392 572",
                            VytvorenoAt = new DateTime(2026, 5, 20, 15, 30, 59, 411, DateTimeKind.Local).AddTicks(4230)
                        },
                        new
                        {
                            Id = 89,
                            Email = "Felician11@gmail.com",
                            Jmeno = "Felicián",
                            Mesto = "Plumlov",
                            Prijmeni = "Burda",
                            Telefon = "754 339 463",
                            VytvorenoAt = new DateTime(2026, 3, 22, 5, 55, 18, 963, DateTimeKind.Local).AddTicks(2962)
                        },
                        new
                        {
                            Id = 90,
                            Email = "Vojmira.Kasal62@volny.cz",
                            Jmeno = "Vojmíra",
                            Mesto = "Králíky",
                            Prijmeni = "Kasal",
                            Telefon = "883 513 077",
                            VytvorenoAt = new DateTime(2024, 7, 6, 22, 2, 39, 414, DateTimeKind.Local).AddTicks(8991)
                        },
                        new
                        {
                            Id = 91,
                            Email = "Sidonie28@centrum.cz",
                            Jmeno = "Sidonie",
                            Mesto = "Libochovice",
                            Prijmeni = "Píša",
                            Telefon = "692 085 934",
                            VytvorenoAt = new DateTime(2025, 5, 26, 16, 0, 2, 968, DateTimeKind.Local).AddTicks(872)
                        },
                        new
                        {
                            Id = 92,
                            Email = "Petronela0@centrum.cz",
                            Jmeno = "Petronela",
                            Mesto = "Kralovice",
                            Prijmeni = "Truhlář",
                            Telefon = "157 828 204",
                            VytvorenoAt = new DateTime(2025, 10, 23, 2, 56, 23, 574, DateTimeKind.Local).AddTicks(6124)
                        },
                        new
                        {
                            Id = 93,
                            Email = "Doris6@seznam.cz",
                            Jmeno = "Doris",
                            Mesto = "Lučany nad Nisou",
                            Prijmeni = "Sobek",
                            Telefon = "030 820 975",
                            VytvorenoAt = new DateTime(2024, 11, 7, 16, 35, 17, 776, DateTimeKind.Local).AddTicks(5623)
                        },
                        new
                        {
                            Id = 94,
                            Email = "Nikodem.Krejci@seznam.cz",
                            Jmeno = "Nikodém",
                            Mesto = "Chodov",
                            Prijmeni = "Krejčí",
                            Telefon = "906 189 456",
                            VytvorenoAt = new DateTime(2025, 10, 7, 6, 16, 20, 250, DateTimeKind.Local).AddTicks(5488)
                        },
                        new
                        {
                            Id = 95,
                            Email = "Sedrik_Dufkova76@centrum.cz",
                            Jmeno = "Sedrik",
                            Mesto = "Skalná",
                            Prijmeni = "Dufková",
                            Telefon = "366 572 035",
                            VytvorenoAt = new DateTime(2026, 3, 14, 7, 7, 10, 365, DateTimeKind.Local).AddTicks(1928)
                        },
                        new
                        {
                            Id = 96,
                            Email = "Salomoun_Sladek@seznam.cz",
                            Jmeno = "Šalomoun",
                            Mesto = "Janské Lázně",
                            Prijmeni = "Sládek",
                            Telefon = "873 436 976",
                            VytvorenoAt = new DateTime(2026, 4, 1, 18, 30, 44, 266, DateTimeKind.Local).AddTicks(113)
                        },
                        new
                        {
                            Id = 97,
                            Email = "Zbynek11@volny.cz",
                            Jmeno = "Zbyněk",
                            Mesto = "Rudolfov",
                            Prijmeni = "Vlk",
                            Telefon = "927 999 740",
                            VytvorenoAt = new DateTime(2025, 8, 18, 18, 23, 35, 665, DateTimeKind.Local).AddTicks(2330)
                        },
                        new
                        {
                            Id = 98,
                            Email = "Drahomila97@volny.cz",
                            Jmeno = "Drahomila",
                            Mesto = "Jaroměřice nad Rokytnou",
                            Prijmeni = "Dobrovolná",
                            Telefon = "423 193 598",
                            VytvorenoAt = new DateTime(2024, 6, 23, 0, 48, 51, 990, DateTimeKind.Local).AddTicks(7294)
                        },
                        new
                        {
                            Id = 99,
                            Email = "Alojzije.Sebela@gmail.com",
                            Jmeno = "Alojzije",
                            Mesto = "Rajhrad",
                            Prijmeni = "Šebela",
                            Telefon = "080 395 664",
                            VytvorenoAt = new DateTime(2024, 11, 11, 8, 18, 27, 354, DateTimeKind.Local).AddTicks(1889)
                        },
                        new
                        {
                            Id = 100,
                            Email = "Lucian33@atlas.cz",
                            Jmeno = "Lucián",
                            Mesto = "Rokytnice v Orlických horách",
                            Prijmeni = "Krupka",
                            Telefon = "917 021 428",
                            VytvorenoAt = new DateTime(2024, 7, 1, 16, 21, 57, 656, DateTimeKind.Local).AddTicks(5352)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
