// <auto-generated />
using System;
using KontaktyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KontaktyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526111814_OpravaSeed")]
    partial class OpravaSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("KontaktyAPI.Models.Kontakt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kontakty");
                });
#pragma warning restore 612, 618
        }
    }
}
