// <auto-generated />
using System;
using KontaktyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KontaktyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("KontaktyAPI.Models.Aktivita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KontaktId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Popis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KontaktId");

                    b.ToTable("Aktivity");
                });

            modelBuilder.Entity("KontaktyAPI.Models.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Web")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Firmy");
                });

            modelBuilder.Entity("KontaktyAPI.Models.Kontakt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pozice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Kontakty");
                });

            modelBuilder.Entity("KontaktyAPI.Models.Schuzka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KontaktId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Misto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Popis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stav")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("KontaktId");

                    b.ToTable("Schuzky");
                });

            modelBuilder.Entity("KontaktyAPI.Models.Aktivita", b =>
                {
                    b.HasOne("KontaktyAPI.Models.Kontakt", "Kontakt")
                        .WithMany("Aktivity")
                        .HasForeignKey("KontaktId");

                    b.Navigation("Kontakt");
                });

            modelBuilder.Entity("KontaktyAPI.Models.Kontakt", b =>
                {
                    b.HasOne("KontaktyAPI.Models.Firma", "Firma")
                        .WithMany("Kontakty")
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("KontaktyAPI.Models.Schuzka", b =>
                {
                    b.HasOne("KontaktyAPI.Models.Firma", "Firma")
                        .WithMany("Schuzky")
                        .HasForeignKey("FirmaId");

                    b.HasOne("KontaktyAPI.Models.Kontakt", "Kontakt")
                        .WithMany("Schuzky")
                        .HasForeignKey("KontaktId");

                    b.Navigation("Firma");

                    b.Navigation("Kontakt");
                });

            modelBuilder.Entity("KontaktyAPI.Models.Firma", b =>
                {
                    b.Navigation("Kontakty");

                    b.Navigation("Schuzky");
                });

            modelBuilder.Entity("KontaktyAPI.Models.Kontakt", b =>
                {
                    b.Navigation("Aktivity");

                    b.Navigation("Schuzky");
                });
#pragma warning restore 612, 618
        }
    }
}
